# Generated by Django 4.0.5 on 2023-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='shifts',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='years',
            field=models.CharField(default=5, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='RMSE',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='predicted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
